### ISSUE TITLE
Fails to load gem 'responsive_active_admin'

### ISSUE THREAD

**Issue by nsallis** [ball-hayden/responsive_active_admin#7]
Hey just wanted to let you know the this gem can't be loaded at all. I'm running ruby 2.3.0 and rails 4.2.5.1 if that helps. Stack trace: 

[my home folder]/.gem/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'responsive_active_admin'. (Bundler::GemRequireError)

**Comment by ball-hayden** [comment]
Hi @Silvertale,

Did you restart your rails server after adding the gem to your `Gemfile` and running `bundle install`?
I've not come across this myself, and I'm running a very similar setup...

**Comment by nsallis** [comment]
Yes, the error happens when I try to start my rails app. I'll try creating a fresh (empty) rails app next week and see if that makes a difference. I'll let you know if that works

-------- Original message --------

**Comment by nsallis** [comment]
Removed activeadmin 1.0.0pre1 and added newest (github) version (1.0.0pre2). Works fine now! seams like it was just an issue with pre1 :)

**Comment by ball-hayden** [comment]
Strange.
Glad that upgrading ActiveAdmin sorted it though...
